/**
 * `read_window` route-level tests (epic #1065 phase 4, issue #1296), driven
 * through `createMcpRoutes` exactly like `mcp-recording-tools.test.ts` and
 * `mcp-overview.test.ts`: real D1, a real `Bun.serve()` fixture upstream, a
 * real `InMemoryCache`. The fixture server's request log is the evidence for
 * the phase 4 definition of done's "no whole-shard read in the Worker": every
 * request against a shard object (`.../0/c/0/<j>`) carries a `Range`, and no
 * such range covers the whole object.
 *
 * The sharded synthetic store (`nm099500`) is generated by
 * `scripts/zarr/generate_mcp_test_fixture.py`'s `build_sharded_level0_fixture`:
 * 4 channels, `chunk_samples` 1000, `shard_samples` 4000, `n_samples` 6500 --
 * shard 0 has 4 inner chunks (local index 2 deliberately ABSENT), shard 1 has
 * 3 (the last truncated to 500 samples). Every present digital sample is
 * `channel * 100 + (global_sample % 1000)`; `scale`/`offset` are `[0.5, 1.0,
 * 1.5, 2.0]` / `[10.0, 20.0, 30.0, 40.0]` (`nm099500-level0-zarr.json`).
 */

import type { Database } from "bun:sqlite";
import { afterAll, beforeAll, beforeEach, describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import type { Hono } from "hono";
import type { ReadWindowOutput } from "../../shared/contract/mcp.js";
import { READ_WINDOW_TASTE_MAX_CHANNEL_SAMPLES } from "../../shared/contract/mcp.js";
import {
  MAX_TASTE_DECODE_SAMPLES,
  exceedsChannelSamplesCap,
  exceedsDecodeBudget,
  maxTasteDurationS,
  roundToSignificantDigits,
} from "../src/mcp/taste.js";
import { type McpRoutesDeps, createMcpRoutes } from "../src/routes/mcp.js";
import { createZarrDataRoutes } from "../src/routes/zarr-data.js";
import type { Bindings } from "../src/types/bindings.js";
import nm000111IndexV1Raw from "./fixtures/mcp/nm000111-index-v1.json";
import nm000329IndexRaw from "./fixtures/mcp/nm000329-index.json";
import nm099500ExpectedRaw from "./fixtures/mcp/nm099500-expected.json";
import nm099500IndexRaw from "./fixtures/mcp/nm099500-index-v3.json";
import { InMemoryCache } from "./helpers/cache.js";
import { freshDb, realD1 } from "./helpers/d1.js";
import { type FixtureServer, startFixtureServer } from "./helpers/fixture-server.js";

type App = Hono<{ Bindings: Bindings }>;

const V3_ID = "nm000329";
const V3_COMMIT = "7172d2d492dad63650f80cdb83352a0e9d4420f7";
const FIRST_STORE_ZARR = "sub-1/ses-0/eeg/sub-1_ses-0_task-imagery_acq-calibration_run-0_eeg.zarr";
const FIRST_STORE_N_CHANNELS = 63;
const FIRST_STORE_N_SAMPLES = 138750;
const FIRST_STORE_DURATION_S = 555;

const V1_ID = "nm000111";
const V1_COMMIT = "510a05377459cf857e60b861ab377bc53b5b5b29";

const ZERO_STORE_ID = "nm500701";
const UNKNOWN_ID = "nm599998";

const SHARD_ID = "nm099500";
// Two variants of the synthetic index, built in beforeAll by REMOVING fields
// rather than committing near-duplicate fixtures: every v3 index in the repo
// carries full geometry, so neither refusal path had anything to exercise it.
const NO_SHARD_GEOM_ID = "nm099501";
const BAD_GEOM_ID = "nm099502";
// A v3 index whose group is as WIDE and as FAST as the real outlier in the
// catalog: on004696's `ieeg_1000hz`, 256 channels at 1000 Hz with
// `chunk_samples` 4000. That shape passes every response-side taste cap and
// then decodes 15.4 M int16 samples, about 31 MB retained, to return 500 KB.
const WIDE_STORE_ID = "nm099503";
const WIDE_N_CHANNELS = 256;
const WIDE_RATE = 1000;
// A v3 index whose shard_samples is NOT an exact multiple of chunk_samples. The
// footer entry count is shard_samples / chunk_samples exactly, so this geometry
// is unplannable -- and it is a fact about someone else's published index, so it
// has to come back as a typed tool error rather than an internal error.
const BAD_DIVISOR_ID = "nm099504";
const SHARD_COMMIT = "c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1";
const SHARD_ZARR = "sub-synth/eeg/sub-synth_task-shardtest_eeg.zarr";
const SHARD_GROUP = "eeg_250hz";
/**
 * Ground truth for the synthetic sharded fixture, read from the generator's
 * own emitted `nm099500-expected.json` rather than re-implemented here.
 *
 * These numbers used to be a hand-written TypeScript mirror of the Python
 * generator's `digital_value`, kept in sync by a comment. Two independent
 * implementations agreeing is a real cross-language check, but nothing failed
 * if they drifted -- the assertions would simply have started checking
 * different, equally plausible values with both sides agreeing. The generator
 * now emits its parameters and a set of spot checks as data, so there is one
 * source of truth; `expectedSpotChecks` below is the authority, and the
 * derived helpers read their constants from the same document.
 */
const EXPECTED = nm099500ExpectedRaw as {
  n_channels: number;
  n_samples: number;
  chunk_samples: number;
  shard_samples: number;
  n_inner_per_shard: number;
  fill_value: number;
  scale: number[];
  offset: number[];
  absent_sample_spans: Array<{ start: number; end: number }>;
  spot_checks: Array<{
    channel: number;
    global_sample: number;
    digital: number;
    physical: number;
    fill_value_substituted: boolean;
    addressable_via_read_window: boolean;
  }>;
};

const SHARD_N_CHANNELS = EXPECTED.n_channels;
const SHARD_CHUNK_SAMPLES = EXPECTED.chunk_samples;
const SHARD_SCALE = EXPECTED.scale;
const SHARD_OFFSET = EXPECTED.offset;

function digitalValue(channel: number, globalSample: number): number {
  return channel * 100 + (globalSample % SHARD_CHUNK_SAMPLES);
}

function expectedPhysical(channel: number, globalSample: number): number {
  const digital = digitalValue(channel, globalSample);
  return roundToSignificantDigits(digital * SHARD_SCALE[channel] + SHARD_OFFSET[channel], 6);
}

function expectedFillPhysical(channel: number): number {
  return roundToSignificantDigits(
    EXPECTED.fill_value * SHARD_SCALE[channel] + SHARD_OFFSET[channel],
    6,
  );
}

const ctx = {
  waitUntil: (p: Promise<unknown>) => {
    p.catch(() => {});
  },
  passThroughOnException: () => {},
} as unknown as ExecutionContext;

function encode(doc: unknown): Uint8Array {
  return new TextEncoder().encode(JSON.stringify(doc));
}

const FIXTURE_PUBLIC_ORIGIN = "https://fixture.nemar.test";

function translatingFetch(real: typeof fetch, fixtureBase: string): typeof fetch {
  return (async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = input instanceof Request ? input.url : String(input);
    if (url.startsWith(FIXTURE_PUBLIC_ORIGIN)) {
      return real(fixtureBase + url.slice(FIXTURE_PUBLIC_ORIGIN.length), init);
    }
    return real(input, init);
  }) as typeof fetch;
}

const MODERN_META = {
  "io.modelcontextprotocol/protocolVersion": "2026-07-28",
  "io.modelcontextprotocol/clientCapabilities": {},
};

interface JsonRpcResponse {
  jsonrpc: "2.0";
  id: number | string | null;
  result?: Record<string, unknown>;
  error?: { code: number; message: string; data?: unknown };
}

async function parseBody(res: Response): Promise<JsonRpcResponse> {
  const text = await res.text();
  const dataLine = text.split("\n").find((l) => l.startsWith("data:"));
  return JSON.parse(dataLine ? dataLine.slice("data:".length).trim() : text);
}

async function callTool(
  app: App,
  database: Bindings,
  id: number,
  name: string,
  args: Record<string, unknown>,
): Promise<{ res: Response; body: JsonRpcResponse }> {
  const res = await app.request(
    "/mcp",
    {
      method: "POST",
      headers: { "Content-Type": "application/json", "Mcp-Method": "tools/call", "Mcp-Name": name },
      body: JSON.stringify({
        jsonrpc: "2.0",
        id,
        method: "tools/call",
        params: { name, arguments: args, _meta: MODERN_META },
      }),
    },
    database,
    ctx,
  );
  return { res, body: await parseBody(res) };
}

function errorTextOf(body: JsonRpcResponse): string {
  expect(body.error).toBeUndefined();
  const result = body.result as { isError?: boolean; content: Array<{ text: string }> };
  expect(result.isError).toBe(true);
  return result.content[0]?.text ?? "";
}

function structuredContentOf(body: JsonRpcResponse): ReadWindowOutput {
  expect(body.error).toBeUndefined();
  const result = body.result as { isError?: boolean; structuredContent?: unknown };
  expect(result.isError).not.toBe(true);
  expect(result.structuredContent).toBeDefined();
  return result.structuredContent as ReadWindowOutput;
}

function textOf(body: JsonRpcResponse): string {
  const result = body.result as { content: Array<{ type: string; text?: string }> };
  const text = result.content.find((c) => c.type === "text");
  return text?.text ?? "";
}

describe("read_window (route)", () => {
  let db: Database;
  let app: App;
  let fixtureServer: FixtureServer;
  let cache: InMemoryCache;
  let shard0Bytes: Uint8Array;
  let shard1Bytes: Uint8Array;
  let level0ZarrJsonBytes: Uint8Array;

  beforeAll(() => {
    fixtureServer = startFixtureServer();

    const rewrittenV3Index = {
      ...nm000329IndexRaw,
      data_base: `${FIXTURE_PUBLIC_ORIGIN}/${V3_ID}/zarr/`,
      contract_base: `${FIXTURE_PUBLIC_ORIGIN}/${V3_ID}/zarr/`,
    };
    fixtureServer.files.set(`${V3_ID}/zarr/index.json`, encode(rewrittenV3Index));
    fixtureServer.files.set(`${V1_ID}/zarr/index.json`, encode(nm000111IndexV1Raw));

    const rewrittenShardIndex = {
      ...nm099500IndexRaw,
      data_base: `${FIXTURE_PUBLIC_ORIGIN}/${SHARD_ID}/zarr/`,
      contract_base: `${FIXTURE_PUBLIC_ORIGIN}/${SHARD_ID}/zarr/`,
    };
    fixtureServer.files.set(`${SHARD_ID}/zarr/index.json`, encode(rewrittenShardIndex));

    // A v3 index whose group carries no `chunk_samples`/`shard_samples`: a
    // recipe is still computable (with those fields null), but a taste is not.
    const shardStore = (rewrittenShardIndex as { stores: Array<Record<string, unknown>> })
      .stores[0];
    const shardGroup = (shardStore.groups as Array<Record<string, unknown>>)[0];
    const { chunk_samples: _cs, shard_samples: _ss, ...groupWithoutGeometry } = shardGroup;
    fixtureServer.files.set(
      `${NO_SHARD_GEOM_ID}/zarr/index.json`,
      encode({
        ...rewrittenShardIndex,
        dataset_id: NO_SHARD_GEOM_ID,
        data_base: `${FIXTURE_PUBLIC_ORIGIN}/${NO_SHARD_GEOM_ID}/zarr/`,
        contract_base: `${FIXTURE_PUBLIC_ORIGIN}/${NO_SHARD_GEOM_ID}/zarr/`,
        stores: [{ ...shardStore, groups: [groupWithoutGeometry] }],
      }),
    );

    // A v3 index whose group has no usable rate at all -- the malformed-index
    // defensive path, distinct from "no sharding geometry".
    fixtureServer.files.set(
      `${BAD_GEOM_ID}/zarr/index.json`,
      encode({
        ...rewrittenShardIndex,
        dataset_id: BAD_GEOM_ID,
        data_base: `${FIXTURE_PUBLIC_ORIGIN}/${BAD_GEOM_ID}/zarr/`,
        contract_base: `${FIXTURE_PUBLIC_ORIGIN}/${BAD_GEOM_ID}/zarr/`,
        stores: [{ ...shardStore, groups: [{ ...shardGroup, rate: 0, n_samples: 0 }] }],
      }),
    );

    fixtureServer.files.set(
      `${BAD_DIVISOR_ID}/zarr/index.json`,
      encode({
        ...rewrittenShardIndex,
        dataset_id: BAD_DIVISOR_ID,
        data_base: `${FIXTURE_PUBLIC_ORIGIN}/${BAD_DIVISOR_ID}/zarr/`,
        contract_base: `${FIXTURE_PUBLIC_ORIGIN}/${BAD_DIVISOR_ID}/zarr/`,
        stores: [
          {
            ...shardStore,
            groups: [{ ...shardGroup, chunk_samples: 1000, shard_samples: 4500 }],
          },
        ],
      }),
    );

    // The decode-budget fixture. Geometry only -- no store objects are served
    // for it, because the guard must refuse before any of them is fetched.
    fixtureServer.files.set(
      `${WIDE_STORE_ID}/zarr/index.json`,
      encode({
        ...rewrittenShardIndex,
        dataset_id: WIDE_STORE_ID,
        data_base: `${FIXTURE_PUBLIC_ORIGIN}/${WIDE_STORE_ID}/zarr/`,
        contract_base: `${FIXTURE_PUBLIC_ORIGIN}/${WIDE_STORE_ID}/zarr/`,
        stores: [
          {
            ...shardStore,
            groups: [
              {
                ...shardGroup,
                n_channels: WIDE_N_CHANNELS,
                rate: WIDE_RATE,
                source_rate_hz: WIDE_RATE,
                n_samples: WIDE_RATE * 600,
                duration_s: 600,
                chunk_samples: 4000,
                shard_samples: 300_000,
              },
            ],
          },
        ],
      }),
    );

    shard0Bytes = new Uint8Array(
      readFileSync(new URL("./fixtures/mcp/nm099500-shard-0.bin", import.meta.url)),
    );
    shard1Bytes = new Uint8Array(
      readFileSync(new URL("./fixtures/mcp/nm099500-shard-1.bin", import.meta.url)),
    );
    level0ZarrJsonBytes = new Uint8Array(
      readFileSync(new URL("./fixtures/mcp/nm099500-level0-zarr.json", import.meta.url)),
    );
    fixtureServer.files.set(
      `${SHARD_ID}/zarr/${SHARD_ZARR}/${SHARD_GROUP}/0/zarr.json`,
      level0ZarrJsonBytes,
    );
    fixtureServer.files.set(`${SHARD_ID}/zarr/${SHARD_ZARR}/${SHARD_GROUP}/0/c/0/0`, shard0Bytes);
    fixtureServer.files.set(`${SHARD_ID}/zarr/${SHARD_ZARR}/${SHARD_GROUP}/0/c/0/1`, shard1Bytes);

    cache = new InMemoryCache();
    const zarrRoutes = createZarrDataRoutes({
      cache: () => cache,
      fetch: (...args: Parameters<typeof fetch>) => fetch(...args),
      s3Base: fixtureServer.url,
    });
    const deps: McpRoutesDeps = {
      onerror: (err) => console.error("[mcp read_window test] transport error", err),
      cache: () => cache,
      fetch: translatingFetch(fetch, fixtureServer.url),
      zarrRoutes,
      rawGithubBase: fixtureServer.url,
    };
    app = createMcpRoutes(deps);
  });

  afterAll(() => {
    fixtureServer.stop();
  });

  function insertDataset(
    datasetId: string,
    cols: Record<string, string | number | null> = {},
  ): void {
    const merged: Record<string, string | number | null> = {
      owner_user_id: -1,
      name: datasetId,
      visibility: "public",
      status: "active",
      is_sandbox: 0,
      ...cols,
    };
    const keys = Object.keys(merged);
    db.query(
      `INSERT INTO datasets (dataset_id, ${keys.join(", ")}) VALUES (?, ${keys.map(() => "?").join(", ")})`,
    ).run(datasetId, ...(keys.map((k) => merged[k]) as never[]));
  }

  beforeEach(() => {
    db = freshDb();
    cache = new InMemoryCache();
    fixtureServer.requestLog.length = 0;
    insertDataset(V3_ID, {
      zarr_status: "ready",
      zarr_store_count: (nm000329IndexRaw as { store_count: number }).store_count,
      zarr_source_commit: V3_COMMIT,
    });
    insertDataset(V1_ID, {
      zarr_status: "ready",
      zarr_store_count: 6,
      zarr_source_commit: V1_COMMIT,
    });
    insertDataset(SHARD_ID, {
      zarr_status: "ready",
      zarr_store_count: 1,
      zarr_source_commit: SHARD_COMMIT,
    });
    insertDataset(NO_SHARD_GEOM_ID, {
      zarr_status: "ready",
      zarr_store_count: 1,
      zarr_source_commit: SHARD_COMMIT,
    });
    insertDataset(BAD_GEOM_ID, {
      zarr_status: "ready",
      zarr_store_count: 1,
      zarr_source_commit: SHARD_COMMIT,
    });
    insertDataset(BAD_DIVISOR_ID, {
      zarr_status: "ready",
      zarr_store_count: 1,
      zarr_source_commit: SHARD_COMMIT,
    });
    insertDataset(WIDE_STORE_ID, {
      zarr_status: "ready",
      zarr_store_count: 1,
      zarr_source_commit: SHARD_COMMIT,
    });
    insertDataset(ZERO_STORE_ID, { zarr_status: "ready", zarr_store_count: 0 });
  });

  function env(database: Database): Bindings {
    return { DB: realD1(database), ENVIRONMENT: "development" } as unknown as Bindings;
  }

  function shardObjectRequests(datasetId: string) {
    return fixtureServer.requestLog.filter(
      (r) => r.url.includes(`${datasetId}/zarr/`) && r.url.includes("/0/c/0/"),
    );
  }

  // ---------------------------------------------------------------------
  // Recipe mode: zero S3 reads
  // ---------------------------------------------------------------------

  describe("recipe mode", () => {
    test("returns mode: recipe with array_path, dtype null, computed slices, envelope, and NO store-object request", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: V3_ID,
        recording: FIRST_STORE_ZARR,
        start_s: 1,
        duration_s: 2,
        channels: [0, 1, 2],
      });
      const output = structuredContentOf(body);
      expect(output.mode).toBe("recipe");
      if (output.mode !== "recipe") return;
      expect(output.recipe.zarr).toBe(FIRST_STORE_ZARR);
      expect(output.recipe.group).toBe("eeg_250hz");
      expect(output.recipe.level).toBe("0");
      expect(output.recipe.array_path).toBe(
        `${FIXTURE_PUBLIC_ORIGIN}/${V3_ID}/zarr/${FIRST_STORE_ZARR}/eeg_250hz/0`,
      );
      expect(output.recipe.dtype).toBeNull();
      expect(output.recipe.codecs).toBeUndefined();
      expect(output.recipe.sample_slice).toEqual({ start: 250, end: 750 });
      expect(output.recipe.channel_slice).toEqual({ start: 0, end: 3 });
      expect(output.envelope.dtype).toBeNull();
      expect(output.envelope.source_commit).toBe(V3_COMMIT);

      // Both-places convention: content also carries the full JSON.
      expect(textOf(body)).toBe(JSON.stringify(output));

      // Zero S3 reads: no request to any store/chunk/zarr.json object.
      const nonIndexRequests = fixtureServer.requestLog.filter(
        (r) => r.url !== `${V3_ID}/zarr/index.json`,
      );
      expect(nonIndexRequests.length).toBe(0);
    });

    test("no channels given: channel_slice is absent", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: V3_ID,
        recording: FIRST_STORE_ZARR,
      });
      const output = structuredContentOf(body);
      expect(output.mode).toBe("recipe");
      if (output.mode !== "recipe") return;
      expect(output.recipe.channel_slice).toBeUndefined();
      // Default start_s 0, duration_s 10 -> sample_slice [0, 2500) at 250 Hz.
      expect(output.recipe.sample_slice).toEqual({ start: 0, end: 2500 });
    });
  });

  // ---------------------------------------------------------------------
  // Taste mode
  // ---------------------------------------------------------------------

  describe("taste mode", () => {
    test("a window inside one present chunk decodes to exact hand-computed physical values", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: SHARD_ID,
        recording: SHARD_ZARR,
        start_s: 1,
        duration_s: 2,
        channels: [0, 1, 2, 3],
        taste: true,
      });
      const output = structuredContentOf(body);
      expect(output.mode).toBe("taste");
      if (output.mode !== "taste") return;
      expect(output.sample_rate_hz).toBe(250);
      expect(output.start_s).toBe(1);
      expect(output.duration_s).toBe(2);
      expect(output.channels).toEqual([0, 1, 2, 3]);
      expect(output.values.length).toBe(4);
      expect(output.values[0].length).toBe(500); // 250 startSample..750

      // startSample 250, endSample 750 -- check first, middle, and last sample of every channel.
      for (let ch = 0; ch < 4; ch++) {
        expect(output.values[ch][0]).toBeCloseTo(expectedPhysical(ch, 250), 9);
        expect(output.values[ch][249]).toBeCloseTo(expectedPhysical(ch, 499), 9);
        expect(output.values[ch][499]).toBeCloseTo(expectedPhysical(ch, 749), 9);
      }

      expect(output.chunks_read).toBe(1);
      expect(output.recipe.dtype).toBe("int16");
      expect(output.recipe.codecs).toBeDefined();
      expect(output.note).toContain("six significant digits");
      expect(output.envelope.dtype).toBe("int16");

      // content is a compact summary, NOT the full JSON dump.
      const contentText = textOf(body);
      expect(contentText).not.toBe(JSON.stringify(output));
      expect(contentText.length).toBeLessThan(JSON.stringify(output).length);
      expect(contentText).toContain("read_window taste");
      expect(contentText).toContain("shape=[4,500]");

      // Every request against the shard object carries a Range; none covers
      // the whole object.
      const shardRequests = shardObjectRequests(SHARD_ID);
      expect(shardRequests.length).toBeGreaterThan(0);
      for (const r of shardRequests) {
        expect(r.range).not.toBe("");
      }
    });

    test("coalescing + the absent fill-value path: a window spanning chunks 1, 2 (absent), 3 of shard 0", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: SHARD_ID,
        recording: SHARD_ZARR,
        start_s: 4, // startSample 1000
        duration_s: 12, // 3000 samples -> endSample 4000 (shard 0 boundary)
        channels: [0, 1, 2, 3],
        taste: true,
      });
      const output = structuredContentOf(body);
      expect(output.mode).toBe("taste");
      if (output.mode !== "taste") return;
      expect(output.values[0].length).toBe(3000);

      // The absent chunk (samples [2000, 3000), local index 2) yields the
      // fill value -- physical == offset[ch] exactly.
      for (let ch = 0; ch < 4; ch++) {
        // local sample 2000 - 1000 (window start) = 1000 within the output array.
        expect(output.values[ch][1000]).toBeCloseTo(expectedFillPhysical(ch), 9);
        expect(output.values[ch][1999]).toBeCloseTo(expectedFillPhysical(ch), 9);
        // Present chunks on either side decode correctly.
        expect(output.values[ch][0]).toBeCloseTo(expectedPhysical(ch, 1000), 9);
        expect(output.values[ch][2000]).toBeCloseTo(expectedPhysical(ch, 3000), 9);
      }

      // Two present chunks (local 1 and 3) were decoded; the absent one (2)
      // contributes no fetch.
      expect(output.chunks_read).toBe(2);

      // The two present-chunk reads must NOT coalesce into one (the absent
      // entry between them breaks the run) -- two separate, non-whole-object
      // Range requests against shard 0.
      const shardRequests = shardObjectRequests(SHARD_ID).filter(
        (r) => !r.range.startsWith("bytes=-"), // exclude the footer suffix-range request
      );
      expect(shardRequests.length).toBe(2);
      for (const r of shardRequests) {
        expect(r.range).not.toBe("");
        expect(r.range).not.toBe(`bytes=0-${shard0Bytes.length - 1}`);
      }
    });

    test("a window spanning two shards reads exactly one chunk from each", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: SHARD_ID,
        recording: SHARD_ZARR,
        start_s: 14, // startSample 3500
        duration_s: 4, // endSample 4500
        channels: [1, 3],
        taste: true,
      });
      const output = structuredContentOf(body);
      expect(output.mode).toBe("taste");
      if (output.mode !== "taste") return;
      expect(output.values.length).toBe(2);
      expect(output.values[0].length).toBe(1000);
      expect(output.values[0][0]).toBeCloseTo(expectedPhysical(1, 3500), 9);
      expect(output.values[0][999]).toBeCloseTo(expectedPhysical(1, 4499), 9);
      expect(output.chunks_read).toBe(2);

      const shard0DataRequests = fixtureServer.requestLog.filter(
        (r) =>
          r.url === `${SHARD_ID}/zarr/${SHARD_ZARR}/${SHARD_GROUP}/0/c/0/0` &&
          !r.range.startsWith("bytes=-"),
      );
      const shard1DataRequests = fixtureServer.requestLog.filter(
        (r) =>
          r.url === `${SHARD_ID}/zarr/${SHARD_ZARR}/${SHARD_GROUP}/0/c/0/1` &&
          !r.range.startsWith("bytes=-"),
      );
      expect(shard0DataRequests.length).toBe(1);
      expect(shard1DataRequests.length).toBe(1);
    });

    test("every request against a shard object carries a Range and never covers the whole object (DoD)", async () => {
      await callTool(app, env(db), 1, "read_window", {
        dataset_id: SHARD_ID,
        recording: SHARD_ZARR,
        start_s: 0,
        duration_s: 26,
        channels: [0, 1, 2, 3],
        taste: true,
      });
      const shardRequests = shardObjectRequests(SHARD_ID);
      expect(shardRequests.length).toBeGreaterThan(0);
      const totalObjectSizes: Record<string, number> = {
        [`${SHARD_ID}/zarr/${SHARD_ZARR}/${SHARD_GROUP}/0/c/0/0`]: shard0Bytes.length,
        [`${SHARD_ID}/zarr/${SHARD_ZARR}/${SHARD_GROUP}/0/c/0/1`]: shard1Bytes.length,
      };
      for (const r of shardRequests) {
        expect(r.range, `request to ${r.url} carried no Range header`).not.toBe("");
        const fullObjectRange = `bytes=0-${totalObjectSizes[r.url] - 1}`;
        expect(r.range).not.toBe(fullObjectRange);
      }

      // Coalescing, proven by REQUEST COUNT, not just "carries a Range": this
      // full-duration window touches shard 0's local chunks 0,1 (adjacent,
      // present -- must coalesce into ONE data request), 2 (absent -- no
      // request), 3 (alone); and shard 1's local chunks 0,1,2 (all adjacent,
      // present -- must coalesce into ONE data request). A planner that
      // never coalesces would still pass every assertion above (each
      // individual request still carries a valid, non-whole-object Range) --
      // this is the assertion a "never coalesce" mutation actually breaks.
      const dataRequests = shardRequests.filter((r) => !r.range.startsWith("bytes=-"));
      const shard0DataRequests = dataRequests.filter((r) => r.url.endsWith("/0/c/0/0"));
      const shard1DataRequests = dataRequests.filter((r) => r.url.endsWith("/0/c/0/1"));
      expect(shard0DataRequests.length).toBe(2); // {0,1} coalesced, {3} alone
      expect(shard1DataRequests.length).toBe(1); // {0,1,2} coalesced
    });

    test("a second identical taste is a cache hit for array metadata and the shard footer: fewer bytes, no zarr.json/footer re-fetch", async () => {
      const args = {
        dataset_id: SHARD_ID,
        recording: SHARD_ZARR,
        start_s: 1,
        duration_s: 2,
        channels: [0, 1, 2, 3],
        taste: true,
      };
      const { body: firstBody } = await callTool(app, env(db), 1, "read_window", args);
      const firstOutput = structuredContentOf(firstBody);
      expect(firstOutput.mode).toBe("taste");
      if (firstOutput.mode !== "taste") return;

      fixtureServer.requestLog.length = 0;
      const { body: secondBody } = await callTool(app, env(db), 2, "read_window", args);
      const secondOutput = structuredContentOf(secondBody);
      expect(secondOutput.mode).toBe("taste");
      if (secondOutput.mode !== "taste") return;

      expect(secondOutput.bytes_read).toBeLessThan(firstOutput.bytes_read);
      expect(secondOutput.values).toEqual(firstOutput.values);

      // No re-fetch of the array metadata or the shard footer -- only the
      // chunk DATA range request remains (decoded windows are never cached).
      const zarrJsonRequests = fixtureServer.requestLog.filter((r) =>
        r.url.endsWith("/0/zarr.json"),
      );
      const footerRequests = fixtureServer.requestLog.filter((r) => r.range.startsWith("bytes=-"));
      expect(zarrJsonRequests.length).toBe(0);
      expect(footerRequests.length).toBe(0);
      const dataRequests = shardObjectRequests(SHARD_ID);
      expect(dataRequests.length).toBe(1);
    });

    test("an unplannable geometry is a TYPED error, not an internal one", async () => {
      // shard_samples 4500 / chunk_samples 1000 is not an exact multiple, so
      // nInnerForShard throws. Every other failure in this tool is a typed
      // isError result; this one used to escape as an opaque JSON-RPC internal
      // error, which reads like a server bug rather than a data problem.
      fixtureServer.requestLog.length = 0;
      const { res, body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: BAD_DIVISOR_ID,
        recording: SHARD_ZARR,
        start_s: 0,
        duration_s: 1,
        channels: [0],
        taste: true,
      });
      expect(res.status).toBe(200);
      // A typed tool result, NOT a JSON-RPC error object.
      expect(body.error).toBeUndefined();
      const text = errorTextOf(body);
      expect(text).toContain("cannot plan a read");
      expect(text).toContain("4500");
      expect(text).toContain("1000");
      // And it costs no I/O beyond the index: the geometry is knowable from
      // index.json alone, so this refuses before even the array-metadata read.
      const nonIndexRequests = fixtureServer.requestLog.filter(
        (r) => !r.url.endsWith("index.json"),
      );
      expect(nonIndexRequests).toEqual([]);
    });

    test("the DECODE budget refuses the on004696 shape before any store read", async () => {
      // 256 channels at 1000 Hz for 60 s with ONE channel requested passes every
      // response-side cap (60 <= 60, 1 <= 64, 60 <= 3840 channel-seconds,
      // 60000 <= 65536 channel-samples) and then decodes 15.4 M samples, because
      // a stored chunk holds every channel in the store. That is the gap this
      // guard closes: the caps bounded the response, never the work.
      fixtureServer.requestLog.length = 0;
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: WIDE_STORE_ID,
        recording: SHARD_ZARR,
        start_s: 0,
        duration_s: 60,
        channels: [0],
        taste: true,
      });
      const text = errorTextOf(body);
      expect(text).toContain("15360000");
      expect(text).toContain(String(MAX_TASTE_DECODE_SAMPLES));
      expect(text).toContain(`${WIDE_N_CHANNELS} channels in the store`);
      // The refusal has to explain WHY fewer channels will not help, or the
      // caller's obvious next move is the one that does not work.
      expect(text).toContain("asking for fewer channels does not reduce this");

      // Nothing was read but the index: no shard footer, no chunk.
      const nonIndexRequests = fixtureServer.requestLog.filter(
        (r) => !r.url.endsWith("index.json"),
      );
      expect(nonIndexRequests).toEqual([]);
    });

    test("the same store WITHIN the budget is not refused for the decode budget", async () => {
      // The mirror: the guard must not be a blanket refusal of wide stores. At
      // 4 s, 256 x 4000 = 1.02 M samples, comfortably under.
      const { body } = await callTool(app, env(db), 2, "read_window", {
        dataset_id: WIDE_STORE_ID,
        recording: SHARD_ZARR,
        start_s: 0,
        duration_s: 4,
        channels: [0],
        taste: true,
      });
      // No store objects are served for this fixture, so this call fails at the
      // FETCH, not at the budget -- which is exactly what proves the budget let
      // it through.
      const result = body.result as { isError?: boolean; content: Array<{ text: string }> };
      const text = result.content.map((b) => b.text).join(" ");
      expect(text).not.toContain(String(MAX_TASTE_DECODE_SAMPLES));
      expect(text).not.toContain("channels in the store");
    });

    test("the channel-samples cap rejects a request naming the rate and the two ways under it", async () => {
      const channels = Array.from({ length: 63 }, (_, i) => i);
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: V3_ID,
        recording: FIRST_STORE_ZARR,
        start_s: 0,
        duration_s: 60,
        channels,
        taste: true,
      });
      const text = errorTextOf(body);
      expect(text).toContain("945000");
      expect(text).toContain("65536");
      expect(text).toContain("250");
      expect(text.toLowerCase()).toContain("fewer channels");

      // Cap enforcement happens BEFORE any store-object read.
      const nonIndexRequests = fixtureServer.requestLog.filter(
        (r) => r.url !== `${V3_ID}/zarr/index.json`,
      );
      expect(nonIndexRequests.length).toBe(0);
    });

    test("out-of-range start_s + duration_s answers a tool error naming the actual bound", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: V3_ID,
        recording: FIRST_STORE_ZARR,
        start_s: 560,
        duration_s: 1,
      });
      const text = errorTextOf(body);
      expect(text).toContain("560");
      expect(text).toContain(String(FIRST_STORE_DURATION_S));
    });

    test("a channel index at or past n_channels answers a tool error naming n_channels", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: V3_ID,
        recording: FIRST_STORE_ZARR,
        channels: [FIRST_STORE_N_CHANNELS],
      });
      const text = errorTextOf(body);
      expect(text).toContain(String(FIRST_STORE_N_CHANNELS));
    });
  });

  // ---------------------------------------------------------------------
  // Shared errors and the v1 refusal
  // ---------------------------------------------------------------------

  describe("shared errors", () => {
    test("a v1 (legacy) index answers a typed refusal, distinct from any other error", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: V1_ID,
        recording: "sub-I003/eeg/sub-I003_task-sleep_eeg.zarr",
      });
      const text = errorTextOf(body);
      expect(text).toContain("v1");
      expect(text.toLowerCase()).toContain("list_recordings");
    });

    test("zarr_store_count 0 answers the shared not-ready error", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: ZERO_STORE_ID,
        recording: "x.zarr",
      });
      const text = errorTextOf(body);
      expect(text).toContain("zarr_status");
    });

    test("an unknown dataset id answers the shared not-found error", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: UNKNOWN_ID,
        recording: "x.zarr",
      });
      const text = errorTextOf(body);
      expect(text.toLowerCase()).toContain("not found");
    });

    test("every structuredContent parses through readWindowOutputSchema", async () => {
      const { readWindowOutputSchema } = await import("../../shared/contract/mcp.js");
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: SHARD_ID,
        recording: SHARD_ZARR,
        start_s: 1,
        duration_s: 1,
        channels: [0],
        taste: true,
      });
      const output = structuredContentOf(body);
      expect(() => readWindowOutputSchema.parse(output)).not.toThrow();
    });

    test("an unknown recording against a ready dataset lists known identifiers", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: SHARD_ID,
        recording: "sub-nope/eeg/sub-nope_task-nope_eeg.zarr",
      });
      const text = errorTextOf(body);
      expect(text).toContain("sub-nope");
      // The error teaches: it names at least one real identifier to use instead.
      expect(text).toContain(SHARD_ZARR);
    });

    test("an unknown group against a known recording lists the real group names", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: SHARD_ID,
        recording: SHARD_ZARR,
        group: "bogus_group",
      });
      const text = errorTextOf(body);
      expect(text).toContain("bogus_group");
      expect(text).toContain(SHARD_GROUP);
    });

    test("a group with no sharding geometry refuses a taste but still serves a recipe", async () => {
      const { body: tasteBody } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: NO_SHARD_GEOM_ID,
        recording: SHARD_ZARR,
        duration_s: 1,
        channels: [0],
        taste: true,
      });
      const text = errorTextOf(tasteBody);
      expect(text.toLowerCase()).toContain("taste");
      // A typed refusal that names the way forward, never a silent downgrade
      // to recipe mode: a caller who asked for numbers must not have to notice
      // that the mode discriminator changed under them.
      expect(shardObjectRequests(NO_SHARD_GEOM_ID).length).toBe(0);

      const { body: recipeBody } = await callTool(app, env(db), 2, "read_window", {
        dataset_id: NO_SHARD_GEOM_ID,
        recording: SHARD_ZARR,
        duration_s: 1,
      });
      const recipe = structuredContentOf(recipeBody);
      expect(recipe.mode).toBe("recipe");
      if (recipe.mode !== "recipe") return;
      expect(recipe.recipe.chunk_samples).toBeNull();
      expect(recipe.recipe.shard_samples).toBeNull();
    });

    test("a group with no usable rate answers the missing-geometry error", async () => {
      const { body } = await callTool(app, env(db), 1, "read_window", {
        dataset_id: BAD_GEOM_ID,
        recording: SHARD_ZARR,
        duration_s: 1,
        channels: [0],
        taste: true,
      });
      const text = errorTextOf(body);
      expect(text.length).toBeGreaterThan(0);
      expect(shardObjectRequests(BAD_GEOM_ID).length).toBe(0);
    });
  });

  // ---------------------------------------------------------------------
  // Ground truth read from the generator's own emitted expectations
  // ---------------------------------------------------------------------

  describe("fixture spot checks (one source of truth for expected values)", () => {
    test("every addressable spot check matches what the tool returns", async () => {
      const addressable = EXPECTED.spot_checks.filter((c) => c.addressable_via_read_window);
      expect(addressable.length).toBeGreaterThan(0);
      for (const check of addressable) {
        // One single-sample window per spot check, so a failure names the
        // exact (channel, sample) pair rather than an index into a big array.
        const startS = check.global_sample / 250;
        const { body } = await callTool(app, env(db), 1, "read_window", {
          dataset_id: SHARD_ID,
          recording: SHARD_ZARR,
          start_s: startS,
          duration_s: 1 / 250,
          channels: [check.channel],
          taste: true,
        });
        const output = structuredContentOf(body);
        expect(output.mode).toBe("taste");
        if (output.mode !== "taste") return;
        expect(output.values[0].length).toBe(1);
        expect(output.values[0][0]).toBeCloseTo(roundToSignificantDigits(check.physical, 6), 9);
        // A padded or absent-chunk sample must also be REPORTED as filled,
        // never handed back looking like recorded signal.
        const filled = output.filled_ranges.some(
          (r) => r.start_sample <= check.global_sample && check.global_sample < r.end_sample,
        );
        expect(filled).toBe(check.fill_value_substituted);
      }
    });

    test("a sample in the boundary chunk's fill padding is refused, not served", async () => {
      // The generator marks these `addressable_via_read_window: false`. The
      // padding is real stored bytes, but a window past the array's extent is
      // a bounds error: padding must never be handed back as if it were
      // recorded signal.
      const unaddressable = EXPECTED.spot_checks.filter((c) => !c.addressable_via_read_window);
      expect(unaddressable.length).toBeGreaterThan(0);
      for (const check of unaddressable) {
        expect(check.global_sample).toBeGreaterThanOrEqual(EXPECTED.n_samples);
        const { body } = await callTool(app, env(db), 1, "read_window", {
          dataset_id: SHARD_ID,
          recording: SHARD_ZARR,
          start_s: check.global_sample / 250,
          duration_s: 1 / 250,
          channels: [check.channel],
          taste: true,
        });
        expect(errorTextOf(body).length).toBeGreaterThan(0);
      }
    });
  });

  // ---------------------------------------------------------------------
  // A Range-ignoring origin must be refused, not mis-sliced
  // ---------------------------------------------------------------------

  describe("a non-compliant origin", () => {
    test("a 200 + full body in answer to a Range request is refused, never sliced", async () => {
      // Without this check the whole-object body would be sliced at
      // `entry.offset - runStart`, which for a run that does not start at byte
      // 0 lands on the shard's EARLIER chunks. Those decode cleanly and have
      // the same shape, so nothing downstream notices: the caller would get
      // real, plausible signal from the wrong point in the recording.
      const key = `${SHARD_ID}/zarr/${SHARD_ZARR}/${SHARD_GROUP}/0/c/0/0`;
      fixtureServer.ignoreRangeForKeys.add(key);
      try {
        const { body } = await callTool(app, env(db), 1, "read_window", {
          dataset_id: SHARD_ID,
          recording: SHARD_ZARR,
          start_s: 4, // startSample 1000: a run that does NOT start at byte 0
          duration_s: 1,
          channels: [0, 1, 2, 3],
          taste: true,
        });
        const text = errorTextOf(body);
        // Assert the PROTOCOL reason, not merely that something was refused.
        // Tolerating a bare 200 here still trips the byte-length check further
        // down (a whole shard is longer than the requested run), so a looser
        // assertion passes even with the status check removed -- which is the
        // downstream coincidence this check exists to stop relying on.
        expect(text).toContain("expected 206");
        expect(text).toContain("ignored Range");
      } finally {
        fixtureServer.ignoreRangeForKeys.delete(key);
      }
    });
  });
});

// -------------------------------------------------------------------------
// The one cap nothing in the schema enforces, asserted at its exact boundary
// -------------------------------------------------------------------------

describe("the decode budget (the store's channels, not the caller's)", () => {
  test("boundary: exactly at the cap passes, one past it does not", () => {
    const cap = 1000;
    expect(exceedsDecodeBudget({ storeChannelCount: 10, windowSamples: 100, cap })).toBe(false);
    expect(exceedsDecodeBudget({ storeChannelCount: 10, windowSamples: 101, cap })).toBe(true);
  });

  test("the caller's channel count is irrelevant: a stored chunk holds them all", () => {
    // The whole reason this guard exists separately from the channel-samples
    // cap. `channels: [0]` does not make the read one channel wide.
    const windowSamples = WIDE_RATE * 60;
    expect(
      exceedsDecodeBudget({
        storeChannelCount: WIDE_N_CHANNELS,
        windowSamples,
        cap: MAX_TASTE_DECODE_SAMPLES,
      }),
    ).toBe(true);
    expect(WIDE_N_CHANNELS * windowSamples).toBe(15_360_000);
  });

  test("maxTasteDurationS names a duration that actually fits", () => {
    const suggested = maxTasteDurationS({
      storeChannelCount: WIDE_N_CHANNELS,
      rate: WIDE_RATE,
      cap: MAX_TASTE_DECODE_SAMPLES,
    });
    expect(suggested).toBeGreaterThan(0);
    expect(
      exceedsDecodeBudget({
        storeChannelCount: WIDE_N_CHANNELS,
        windowSamples: Math.floor(suggested * WIDE_RATE),
        cap: MAX_TASTE_DECODE_SAMPLES,
      }),
    ).toBe(false);
  });

  test("a degenerate store (0 channels or 0 rate) suggests 0 rather than Infinity", () => {
    expect(maxTasteDurationS({ storeChannelCount: 0, rate: 250, cap: 1000 })).toBe(0);
    expect(maxTasteDurationS({ storeChannelCount: 4, rate: 0, cap: 1000 })).toBe(0);
  });
});

describe("exceedsChannelSamplesCap", () => {
  const cap = READ_WINDOW_TASTE_MAX_CHANNEL_SAMPLES;

  test("the cap is 65536", () => {
    expect(cap).toBe(65_536);
  });

  test("exactly at the cap is allowed", () => {
    expect(exceedsChannelSamplesCap({ channelCount: 64, windowSamples: 1024, cap })).toBe(false);
    expect(exceedsChannelSamplesCap({ channelCount: 1, windowSamples: cap, cap })).toBe(false);
  });

  test("one channel-sample past the cap is rejected", () => {
    // The boundary the end-to-end test cannot reach: its request is ~14x the
    // cap, so `>` vs `>=` there is indistinguishable.
    expect(exceedsChannelSamplesCap({ channelCount: 1, windowSamples: cap + 1, cap })).toBe(true);
    expect(exceedsChannelSamplesCap({ channelCount: 64, windowSamples: 1025, cap })).toBe(true);
  });

  test("it is a product, not a sum", () => {
    // 2 x 40000 = 80000 exceeds the cap; 2 + 40000 = 40002 does not. A
    // sum-instead-of-product bug would wrongly ALLOW this request, and the
    // existing end-to-end test (~14x over the cap on both readings) cannot
    // tell the two apart.
    expect(exceedsChannelSamplesCap({ channelCount: 2, windowSamples: 40_000, cap })).toBe(true);
    // The converse: 1 x 65536 is exactly at the cap and allowed, while
    // 1 + 65536 would exceed it, so a sum would wrongly REJECT this one.
    expect(exceedsChannelSamplesCap({ channelCount: 1, windowSamples: cap, cap })).toBe(false);
  });
});
