/**
 * Sandbox Dataset Generation for NEMAR CLI
 *
 * Generates a minimal valid BIDS dataset for sandbox training.
 * The dataset contains placeholder data to test the full upload pipeline
 * without using real research data.
 */

import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** Sandbox dataset paths */
export interface SandboxDatasetPaths {
  root: string;
  datasetDescription: string;
  participants: string;
  readme: string;
  subjectDir: string;
  eegDir: string;
  edfFile: string;
  sidecarJson: string;
}

/**
 * Generate paths for a sandbox dataset
 */
export function getSandboxPaths(rootDir: string): SandboxDatasetPaths {
  const subjectDir = join(rootDir, "sub-01");
  const eegDir = join(subjectDir, "eeg");

  return {
    root: rootDir,
    datasetDescription: join(rootDir, "dataset_description.json"),
    participants: join(rootDir, "participants.tsv"),
    readme: join(rootDir, "README"),
    subjectDir,
    eegDir,
    edfFile: join(eegDir, "sub-01_task-rest_eeg.edf"),
    sidecarJson: join(eegDir, "sub-01_task-rest_eeg.json"),
  };
}

/**
 * Generate a minimal valid BIDS dataset for sandbox training
 *
 * Creates:
 * - dataset_description.json (required)
 * - participants.tsv (required for subject data)
 * - README
 * - sub-01/eeg/sub-01_task-rest_eeg.edf (~500KB random data)
 * - sub-01/eeg/sub-01_task-rest_eeg.json (sidecar)
 *
 * @param outputDir - Directory to create the dataset in (will be created if needed)
 * @returns Paths to all generated files
 */
export function generateSandboxDataset(outputDir?: string): SandboxDatasetPaths {
  // Use temp directory if not specified
  const rootDir = outputDir || join(tmpdir(), `nemar-sandbox-${Date.now()}`);
  const paths = getSandboxPaths(rootDir);

  // Create directory structure
  mkdirSync(paths.eegDir, { recursive: true });

  // Generate dataset_description.json (required by BIDS)
  const datasetDescription = {
    Name: "NEMAR Sandbox Training Dataset",
    BIDSVersion: "1.9.0",
    DatasetType: "raw",
    License: "CC0",
    Authors: ["NEMAR CLI Training"],
    HowToAcknowledge: "This is a sandbox dataset for testing the NEMAR upload workflow.",
    DatasetDOI: "n/a",
  };
  writeFileSync(paths.datasetDescription, JSON.stringify(datasetDescription, null, 2));

  // Generate participants.tsv
  const participantsTsv = "participant_id\tage\tsex\nsub-01\t25\tM\n";
  writeFileSync(paths.participants, participantsTsv);

  // Generate README
  const readme = `# NEMAR Sandbox Training Dataset

This is a placeholder dataset generated by the NEMAR CLI for sandbox training.

## Purpose

This dataset is used to:
1. Verify your DataLad, git-annex, and SSH setup
2. Test the full upload pipeline to NEMAR
3. Familiarize you with the upload workflow

## Contents

- 1 subject (sub-01)
- 1 EEG recording (resting state)
- Random noise data (~500KB)

## Note

This dataset contains randomly generated data and is not suitable for analysis.
It will be automatically cleaned up from the sandbox environment.
`;
  writeFileSync(paths.readme, readme);

  // Generate EDF file with random data
  generateRandomEdfFile(paths.edfFile, 500);

  // Generate sidecar JSON
  const sidecarJson = {
    TaskName: "rest",
    TaskDescription: "Resting state with eyes closed (sandbox test data)",
    SamplingFrequency: 256,
    PowerLineFrequency: 60,
    SoftwareFilters: "n/a",
    EEGChannelCount: 4,
    EEGReference: "Cz",
    RecordingType: "continuous",
    RecordingDuration: 60,
    Manufacturer: "NEMAR CLI Sandbox",
  };
  writeFileSync(paths.sidecarJson, JSON.stringify(sidecarJson, null, 2));

  return paths;
}

/**
 * Generate a random EDF file with valid header structure
 *
 * EDF format:
 * - 256 bytes main header
 * - 256 bytes per signal header
 * - Data records
 *
 * @param outputPath - Path to write the EDF file
 * @param sizeKb - Approximate size in KB (default 500)
 */
export function generateRandomEdfFile(outputPath: string, sizeKb = 500): void {
  const numChannels = 4;
  const sampleRate = 256;
  const numRecords = Math.floor((sizeKb * 1024) / (numChannels * 2 * sampleRate));

  // Main header (256 bytes)
  const header = Buffer.alloc(256, " ");

  // Version (8 bytes)
  header.write("0       ", 0, 8);

  // Patient ID (80 bytes)
  header.write("X X X NEMAR_Sandbox_Subject", 8, 80);

  // Recording ID (80 bytes)
  header.write("Startdate 01-JAN-2024 X NEMAR_CLI_Sandbox", 88, 80);

  // Start date (8 bytes) - dd.mm.yy
  header.write("01.01.24", 168, 8);

  // Start time (8 bytes) - hh.mm.ss
  header.write("00.00.00", 176, 8);

  // Header bytes (8 bytes)
  const headerBytes = 256 + numChannels * 256;
  header.write(headerBytes.toString().padEnd(8), 184, 8);

  // Reserved (44 bytes)
  header.write("EDF+C".padEnd(44), 192, 44);

  // Number of data records (8 bytes)
  header.write(numRecords.toString().padEnd(8), 236, 8);

  // Duration of data record in seconds (8 bytes)
  header.write("1       ", 244, 8);

  // Number of signals (4 bytes)
  header.write(numChannels.toString().padEnd(4), 252, 4);

  // Signal headers (256 bytes each)
  const signalHeader = Buffer.alloc(numChannels * 256, " ");
  const channelNames = ["Fp1", "Fp2", "C3", "C4"];

  // Write signal header fields (each field is numChannels * fieldSize)
  const fieldSize = 16;
  const fields = [
    { offset: 0, size: 16, values: channelNames }, // Label
    { offset: 16 * numChannels, size: 80, values: Array(numChannels).fill("EEG electrode") }, // Transducer
    { offset: 96 * numChannels, size: 8, values: Array(numChannels).fill("uV") }, // Physical dimension
    { offset: 104 * numChannels, size: 8, values: Array(numChannels).fill("-500") }, // Physical min
    { offset: 112 * numChannels, size: 8, values: Array(numChannels).fill("500") }, // Physical max
    { offset: 120 * numChannels, size: 8, values: Array(numChannels).fill("-32768") }, // Digital min
    { offset: 128 * numChannels, size: 8, values: Array(numChannels).fill("32767") }, // Digital max
    { offset: 136 * numChannels, size: 80, values: Array(numChannels).fill("") }, // Prefiltering
    { offset: 216 * numChannels, size: 8, values: Array(numChannels).fill(sampleRate.toString()) }, // Samples per record
    { offset: 224 * numChannels, size: 32, values: Array(numChannels).fill("") }, // Reserved
  ];

  for (const field of fields) {
    for (let i = 0; i < numChannels; i++) {
      const value = field.values[i].padEnd(field.size);
      signalHeader.write(value, field.offset + i * field.size, field.size);
    }
  }

  // Generate random data records
  // Each record: numChannels * sampleRate * 2 bytes (16-bit integers)
  const recordSize = numChannels * sampleRate * 2;
  const dataBuffer = Buffer.alloc(numRecords * recordSize);

  // Fill with random noise (simulating EEG signal)
  for (let i = 0; i < dataBuffer.length; i += 2) {
    // Random 16-bit integer centered around 0
    const value = Math.floor(Math.random() * 65536) - 32768;
    dataBuffer.writeInt16LE(value, i);
  }

  // Combine all parts and write
  const edfFile = Buffer.concat([header, signalHeader, dataBuffer]);
  writeFileSync(outputPath, edfFile);
}

/**
 * Clean up a sandbox dataset directory
 *
 * Uses chmod to fix git-annex restricted permissions before removal.
 *
 * @param datasetPath - Path to the sandbox dataset to remove
 */
export function cleanupSandboxDataset(datasetPath: string): void {
  const { execSync } = require("node:child_process");
  try {
    // Git-annex creates files with restricted permissions; fix before removal
    execSync(`chmod -R u+w "${datasetPath}" 2>/dev/null || true`, { stdio: "ignore" });
    rmSync(datasetPath, { recursive: true, force: true });
  } catch {
    // If Node.js rmSync fails, fall back to shell rm -rf
    try {
      execSync(`rm -rf "${datasetPath}"`, { stdio: "ignore" });
    } catch {
      // Best effort cleanup; ignore errors
    }
  }
}

/**
 * Get the size of a generated sandbox dataset in bytes
 */
export function getSandboxDatasetSize(paths: SandboxDatasetPaths): number {
  const { statSync } = require("node:fs");
  let totalSize = 0;

  const files = [
    paths.datasetDescription,
    paths.participants,
    paths.readme,
    paths.edfFile,
    paths.sidecarJson,
  ];

  for (const file of files) {
    try {
      totalSize += statSync(file).size;
    } catch {
      // File doesn't exist, skip
    }
  }

  return totalSize;
}
