-- Single-use ORCID link intents for the CLI handoff
-- (ADR 0044, epic #1250 phase #1266; PR #1269 review item A3).
--
-- WHAT THIS CLOSES. `POST /auth/orcid/cli-start` mints a signed, short-lived
-- intent naming the account it was created for, and the browser that finishes
-- the ORCID flow carries no NEMAR session -- that is the whole point, since it
-- was opened from a terminal. The signature makes the intent unforgeable, but
-- a signature alone does not make it UNREPEATABLE: anyone holding the URL
-- (browser history, a referrer, a shoulder) could complete it again inside the
-- ten-minute window, and the consequence is permanent. ADR 0041 makes a DOI
-- cite the account the iD is attached to, and ADR 0043 then refuses the
-- rightful owner their own iD because it is "already on a live account".
--
-- So the intent gets a server-side nonce and is CONSUMED at the callback.
-- One browser completion per intent, whatever its outcome; a replay finds
-- `consumed_at` already set and is refused before anything is linked.
--
-- WHY A TABLE. `auth_codes` is the only comparable short-lived store and it is
-- keyed by email address for a 6-digit secret with an attempt counter -- none
-- of which fits a 256-bit nonce for an account-scoped OAuth intent. Reusing it
-- would mean an `email` column carrying something that is not an email and a
-- `code_hash` carrying something nobody types. This table is four columns and
-- holds nothing for longer than ten minutes.
--
-- LIFECYCLE. Rows are pruned opportunistically at mint time (every
-- `cli-start` deletes what has expired), so the table needs no cron and
-- cannot grow past the intents minted in one ten-minute window. Nothing here
-- is a secret: the nonce is meaningless without the HMAC-signed state that
-- carries it, and that signature is keyed with ENCRYPTION_KEY.

CREATE TABLE IF NOT EXISTS orcid_link_intents (
  -- 256 bits of URL-safe randomness, generated by `generateCsrf()`. Primary
  -- key rather than a surrogate id: the nonce IS the identity of the intent,
  -- and a UNIQUE constraint on it is what makes "consume once" enforceable.
  nonce TEXT PRIMARY KEY,
  -- The account the intent was minted FOR. Also inside the signed state; kept
  -- here so the interstitial can name the account without trusting anything
  -- the browser sent, and so a deleted account's intents go with it.
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- 'link' or 'relink'. Never 'login': a CLI flow always acts on an account
  -- that already exists.
  mode TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL,
  -- Set by the callback the first time the intent completes. A second
  -- completion finds it non-NULL and is refused.
  consumed_at TEXT
);

-- Drives the opportunistic prune and the "is this still usable" read.
CREATE INDEX IF NOT EXISTS idx_orcid_link_intents_expires
  ON orcid_link_intents(expires_at);
