/**
 * Typed access to the pinned Neurobagel vocabulary snapshot.
 *
 * The snapshot files under ./vocab/ are generated by
 * scripts/neurobagel/generate-vocab.ts from commit-pinned Neurobagel
 * repositories and are never edited by hand.
 * Everything the transform may emit as a controlled term, a namespace or a
 * JSON-LD context comes from here, so a term can only reach an output if the
 * pinned vocabulary says it exists.
 *
 * This module imports only the small snapshot (about 10 KB).
 * The full diagnosis and assessment vocabularies are in
 * vocab/diagnosis-terms.json and vocab/assessment-terms.json and are imported
 * only by code that needs to check an arbitrary term (the curation loader, the
 * term-verification test), never by the transform's hot path.
 *
 * Pure: no I/O.
 */

import snapshotJson from "./vocab/snapshot.json";

export interface VocabTerm {
  identifier: string;
  label: string;
}

export interface ImagingModalityTerm extends VocabTerm {
  abbreviation: string;
  data_type: string;
}

export interface PinnedFile {
  blob_sha: string;
  bytes: number;
  sha256: string;
}

export interface VocabSnapshot {
  snapshot_version: number;
  bagel_version: string;
  /** JSON-LD `@context` exactly as the pinned `bagel` release writes it. */
  context: Record<string, unknown>;
  namespaces: Record<string, string>;
  /** Neurobagel age format terms by id (`FromFloat`, `FromRange`, ...). */
  age_formats: Record<string, VocabTerm>;
  /** Sex terms by lower-case English name (`male`, `female`, `other`). */
  sex: Record<string, VocabTerm>;
  /** Imaging modality terms by BIDS suffix or datatype (`eeg`, `meg`, `T1w`, ...). */
  imaging_modalities: Record<string, ImagingModalityTerm>;
  healthy_control: VocabTerm;
  /** Standardized variables by id (`ParticipantID`, `Age`, `Sex`, `Diagnosis`, ...). */
  variables: Record<string, VocabTerm>;
  term_files: Record<string, { file: string; terms: number }>;
  pins: {
    api: { commit: string; files: Record<string, PinnedFile>; repo: string; tag: string };
    bagel: {
      commit: string;
      files: Record<string, PinnedFile>;
      pypi: string;
      repo: string;
      tag: string;
    };
    communities: { commit: string; files: Record<string, PinnedFile>; repo: string };
    recipes: { commit: string; files: Record<string, PinnedFile>; repo: string };
  };
}

export const VOCAB = snapshotJson as unknown as VocabSnapshot;

/** The term for a controlled value, or a thrown error: an unpinned term must never be emitted. */
function pinned<T>(table: Record<string, T>, key: string, what: string): T {
  const term = table[key];
  if (term === undefined) throw new Error(`pinned Neurobagel vocabulary has no ${what} "${key}"`);
  return term;
}

export const sexTerm = (name: "male" | "female" | "other"): VocabTerm =>
  pinned(VOCAB.sex, name, "sex term");

export const ageFormatTerm = (id: string): VocabTerm => pinned(VOCAB.age_formats, id, "age format");

export const variableTerm = (id: string): VocabTerm =>
  pinned(VOCAB.variables, id, "standardized variable");

/**
 * The BIDS datatype directories NEMAR maps to an imaging modality term.
 *
 * The pinned vocabulary also holds `pet` and several image suffixes, but NEMAR
 * is an electrophysiology archive: only `eeg` and `meg` are mapped, and every
 * other datatype (iEEG, EMG, NIRS, motion, behavior, anatomy, ...) is dropped
 * and counted in the report.
 * Widening this list is an output change and needs a transform version bump.
 */
export const MAPPED_DATATYPES: readonly string[] = ["eeg", "meg"];

/**
 * The imaging modality term for a BIDS datatype directory, or null when NEMAR
 * does not map it.
 * A null here is the answer, never a prompt to pick a near neighbour: an
 * electromyography recording mapped to EEG would be a false statement in a
 * public index.
 * The term itself is read from the pinned vocabulary, and it must agree that
 * its own data type is the datatype asked for.
 */
export function modalityTermForDatatype(datatype: string): ImagingModalityTerm | null {
  if (!MAPPED_DATATYPES.includes(datatype)) return null;
  const term = pinned(VOCAB.imaging_modalities, datatype, "imaging modality for datatype");
  if (term.data_type !== datatype) {
    throw new Error(`pinned imaging modality "${datatype}" has data type "${term.data_type}"`);
  }
  return term;
}

/** The namespace prefix of an `ns:id` identifier. */
export function namespaceOf(identifier: string): string {
  return identifier.slice(0, identifier.indexOf(":"));
}
