"""Tests for scripts/patch_duration.py (Tier-2 duration via biosigIO full read).

No mocks: builds a real git repo with a real EDF (generated by pyedflib, which
biosigIO bundles) committed as a plain git blob, so materialize_recording writes
it directly and biosigIO reads it -- no S3 needed. Skipped when biosigio/pyedflib
are absent (local dev without the zarr deps); CI installs scripts/zarr/requirements.txt.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent

try:
    import numpy as np
    import pyedflib

    HAVE_PYEDFLIB = True
except ImportError:
    HAVE_PYEDFLIB = False

try:
    import biosigio  # noqa: F401

    HAVE_BIOSIGIO = True
except ImportError:
    HAVE_BIOSIGIO = False

NEEDS_DEPS = unittest.skipUnless(
    HAVE_PYEDFLIB and HAVE_BIOSIGIO,
    "needs pyedflib + biosigio (CI installs scripts/zarr/requirements.txt)",
)

EDF_REL = "sub-01/eeg/sub-01_task-rest_eeg.edf"
FS, SECS, N_CH = 256, 10, 2
EXPECTED_DURATION = float(SECS)  # 10.0 s
EXPECTED_NTIMES = FS * SECS  # 2560


def write_edf(path: Path, *, fs: int = FS, secs: int = SECS, n_ch: int = N_CH) -> None:
    """Write a real, EDF+-compliant file with a known duration."""
    w = pyedflib.EdfWriter(str(path), n_ch, file_type=pyedflib.FILETYPE_EDFPLUS)
    headers = [
        dict(
            label=f"EEG{i}",
            dimension="uV",
            sample_frequency=fs,
            physical_min=-200.0,
            physical_max=200.0,
            digital_min=-32768,
            digital_max=32767,
            transducer="",
            prefilter="",
        )
        for i in range(n_ch)
    ]
    w.setSignalHeaders(headers)
    sig = [
        (np.sin(np.arange(fs * secs) / fs * 2 * np.pi * 10) * 100).astype(np.float64)
        for _ in range(n_ch)
    ]
    w.writeSamples(sig)
    w.close()


def _git(repo: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def setup_repo(repo: Path, *, primary_bytes: bytes | None = None) -> None:
    """Real git repo with the primary committed as a plain git blob, tagged
    v1.0.0. No git-annex, so materialize_recording writes the blob directly
    (no S3)."""
    repo.mkdir(parents=True, exist_ok=True)
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "t@t")
    _git(repo, "config", "user.name", "t")
    edf = repo / EDF_REL
    edf.parent.mkdir(parents=True, exist_ok=True)
    if primary_bytes is None:
        write_edf(edf)
    else:
        edf.write_bytes(primary_bytes)
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "init")
    _git(repo, "tag", "v1.0.0")


def import_patch():
    sys.path.insert(0, str(HERE))
    import patch_duration

    return patch_duration


def base_record(**ss) -> dict:
    summary = {
        "nchans": 2,
        "ntimes": None,
        "recording_duration": None,
        "channel_type_counts": {"EEG": 2},
    }
    summary.update(ss)
    return {
        "schema_version": "0.3.0",
        "doc_type": "record",
        "dataset": "nm099999",
        "bids_relpath": EDF_REL,
        "modality": "EEG",
        "signal_summary": summary,
    }


@NEEDS_DEPS
class PatchDurationTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.repo = Path(self.tmp) / "repo"
        self.pd = import_patch()

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _patch(self, records):
        return self.pd.patch_records(
            records,
            repo_dir=str(self.repo),
            bucket="nemar",
            dataset_id="nm099999",
            version="1.0.0",
        )

    def test_fills_duration_from_real_edf_git_blob(self):
        setup_repo(self.repo)
        records = [base_record()]
        filled, gaps = self._patch(records)
        self.assertEqual((filled, gaps), (1, 1))
        ss = records[0]["signal_summary"]
        self.assertAlmostEqual(ss["recording_duration"], EXPECTED_DURATION, places=3)
        self.assertEqual(ss["ntimes"], EXPECTED_NTIMES)

    def test_already_resolved_duration_is_untouched(self):
        setup_repo(self.repo)
        records = [base_record(recording_duration=42.0, ntimes=99)]
        filled, gaps = self._patch(records)
        # Not a gap -> never read, never changed (idempotent vs Tier-1 output).
        self.assertEqual((filled, gaps), (0, 0))
        self.assertEqual(records[0]["signal_summary"]["recording_duration"], 42.0)
        self.assertEqual(records[0]["signal_summary"]["ntimes"], 99)

    def test_unreadable_primary_stays_null_best_effort(self):
        # >1024 bytes so it is not mistaken for an annex pointer; garbage so
        # biosigIO can't read it -> must stay null without raising.
        setup_repo(self.repo, primary_bytes=b"NOT-AN-EDF" * 256)
        records = [base_record()]
        filled, gaps = self._patch(records)
        self.assertEqual((filled, gaps), (0, 1))
        self.assertIsNone(records[0]["signal_summary"]["recording_duration"])

    def test_idempotent_rerun(self):
        setup_repo(self.repo)
        records = [base_record()]
        self._patch(records)
        first = records[0]["signal_summary"]["recording_duration"]
        # Second pass: no longer a gap -> no-op, value stable.
        filled, gaps = self._patch(records)
        self.assertEqual((filled, gaps), (0, 0))
        self.assertEqual(records[0]["signal_summary"]["recording_duration"], first)

    def test_preserves_existing_tier1_ntimes(self):
        # ntimes set by Tier-1 (sidecar SF*RD) but duration null is impossible by
        # construction; still, if ntimes is present we must not clobber it.
        setup_repo(self.repo)
        records = [base_record(ntimes=1234)]
        self._patch(records)
        self.assertEqual(records[0]["signal_summary"]["ntimes"], 1234)
        self.assertAlmostEqual(
            records[0]["signal_summary"]["recording_duration"], EXPECTED_DURATION, places=3
        )


if __name__ == "__main__":
    unittest.main()
