/**
 * Test-layer helper: compile an ajv (JSON Schema 2020-12) validator for the
 * vendored neuroschema dataset bundle (epic #896, #898).
 *
 * Lives under test/ (not shared/contract/) on purpose: ajv is a test-only
 * concern, so the shared contract stays zero-dependency-beyond-zod and
 * extraction-clean. The bundle JSON in shared/contract/neuroschema/ is pure
 * data (regenerated by build-vendor.mjs from the neuroschema repo).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { ValidateFunction } from "ajv";
import addFormats from "ajv-formats";
import Ajv2020 from "ajv/dist/2020";

interface Bundle {
  root: string;
  schemas: Array<{ $id: string } & Record<string, unknown>>;
}

const BUNDLE_PATH = join(import.meta.dir, "../../shared/contract/neuroschema/dataset.bundle.json");

/** Compile a validator for the neuroschema dataset root from the vendored bundle. */
export function compileNeuroschemaDatasetValidator(): ValidateFunction {
  const bundle = JSON.parse(readFileSync(BUNDLE_PATH, "utf8")) as Bundle;
  // strict:false tolerates neuroschema's descriptive keywords; allErrors for
  // readable failures. Each vendored schema carries its own nsc:/ $id, so
  // cross-file $refs (rewritten by build-vendor.mjs) resolve on addSchema.
  const ajv = new Ajv2020({ allErrors: true, strict: false });
  addFormats(ajv);
  for (const schema of bundle.schemas) ajv.addSchema(schema);
  const validate = ajv.getSchema(bundle.root);
  if (!validate) throw new Error(`neuroschema root ${bundle.root} not found in bundle`);
  return validate;
}

/** Format ajv errors compactly for test output. */
export function formatAjvErrors(validate: ValidateFunction): string {
  return (validate.errors ?? []).map((e) => `${e.instancePath || "/"} ${e.message}`).join("; ");
}
