/**
 * Test-layer helper: compile an ajv (JSON Schema 2020-12) validator for the
 * vendored neuroschema dataset bundle (epic #896, #898).
 *
 * Lives under test/ (not shared/contract/) on purpose: ajv is a test-only
 * concern, so the shared contract stays zero-dependency-beyond-zod and
 * extraction-clean. The bundle JSON in shared/contract/neuroschema/ is pure
 * data (regenerated by build-vendor.mjs from the neuroschema repo).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { ValidateFunction } from "ajv";
import addFormats from "ajv-formats";
import Ajv2020 from "ajv/dist/2020";
import { NEUROSCHEMA_VERSION } from "../../shared/contract/index.js";

interface Bundle {
  root: string;
  schemas: Array<{ $id: string } & Record<string, unknown>>;
}

const BUNDLE_PATH = join(import.meta.dir, "../../shared/contract/neuroschema/dataset.bundle.json");

/** Compile a validator for the neuroschema dataset root from the vendored bundle. */
export function compileNeuroschemaDatasetValidator(): ValidateFunction {
  const bundle = JSON.parse(readFileSync(BUNDLE_PATH, "utf8")) as Bundle;
  // strict:false tolerates neuroschema's descriptive keywords; allErrors for
  // readable failures. Each vendored schema carries its own nsc:/ $id, so
  // cross-file $refs (rewritten by build-vendor.mjs) resolve on addSchema.
  const ajv = new Ajv2020({ allErrors: true, strict: false });
  addFormats(ajv);
  for (const schema of bundle.schemas) ajv.addSchema(schema);
  const validate = ajv.getSchema(bundle.root);
  if (!validate) throw new Error(`neuroschema root ${bundle.root} not found in bundle`);
  return validate;
}

/** Format ajv errors compactly for test output. */
export function formatAjvErrors(validate: ValidateFunction): string {
  return (validate.errors ?? []).map((e) => `${e.instancePath || "/"} ${e.message}`).join("; ");
}

/**
 * The `schema_version` a LIVE response may carry: the same MAJOR.MINOR as
 * `NEUROSCHEMA_VERSION`, any PATCH.
 *
 * The live checks run against a deployed backend, and a pull request that bumps
 * `NEUROSCHEMA_VERSION` (a PATCH, since neuroschema 0.x treats additive fields
 * as patches) cannot be deployed before its own CI runs. Pinning the exact
 * string there turns every such release red until the deploy lands, for a
 * difference that is harmless by definition. A different MINOR still fails: that
 * is a breaking change or a new extension namespace, and the live backend must
 * agree on it. The exact
 * version is pinned by the pure tests (`test/contract-schemas.test.ts` and the
 * bundle stamp check in `test/contract-neuroschema.test.ts`).
 */
export const NEUROSCHEMA_LINE_RE = new RegExp(
  `^${NEUROSCHEMA_VERSION.split(".").slice(0, 2).join(".").replace(/\./g, "\\.")}\\.\\d+$`,
);
